config/routes.rb
Rails.application.routes.draw do
get    'sessions/new'
get    'users/new'
root   'static_pages#home'
get    'about'   => 'static_pages#about'
get    'help'    => 'static_pages#help'
get    'contact' => 'static_pages#contact'
get    'signup'  => 'users#new'
get    'login'   => 'sessions#new'
post   'login'   => 'sessions#create'
delete 'logout'  => 'sessions#destroy'
resources :users

  
  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
     flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def login
  end
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def show
    @user = User.find(params[:id])
 end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the CS 518 App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
  
end 

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "CS 518 Web App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href=""></a>
    <a href=""></a>
  </small>
  <nav>
    <ul>
     
      <li><%= link_to "Contact", contact_path %></li> 
     
 
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "CS 518 Web App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Source", help_path %></li>
        <% if logged_in? %>
 
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
     <%= debug(params) if Rails.env.development? %> 
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>Free Juice Recipes</h1>
    <p>
      <center>
      <li><a href="https://juicerecipes.com/"><em>Juice Recipe Link 1</li>
      <li><a href="http://www.rebootwithjoe.com/recipes/"><em>Juice Recipe Link 2</li>
      <li><a href="http://allrecipes.com/recipes/drinks/juice/"><em>Juice Recipe Link 3</li>
      <li><a href="http://www.all-about-juicing.com/juicer-recipes.html"><em>Juice Recipe Link 4</li>
      <li><a href="http://juicing-for-health.com/fun-free-recipes/juicer-recipes.html"><em>Juice Recipe Link 5</li>
      <li><a href="https://www.juicemaster.com/us/recipes/juices"><em>Juice Recipe Link 6</li>
      </center>
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | CS 518 Contacts</title>
  </head>
  <body>
    <h1>Contact Info</h1>
    <p>Emails:</p>
    <p>
      Brian Everetts: everetb@sunyit.edu
    </p>
    <p>
      Antonia Mondello: mondela@sunyit.edu
    </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Source") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Source page</title>
  </head>
  <body>
    <h1>Source</h1>
    <p>
      To visit source code here:
      <a href="https://bitbucket.org/everetb/cs_app"> BitBucket
      </a>
     
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome CS 518 Web App</h1>

  <h2>
    This is the home page for the Juice Web App. Create your login below. 
  </h2>

  <table>
    
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  <p>    </p>
  <%= link_to "See links to Juice Recipes", about_path, class: "btn btn-lg btn-primary" %>
  </table>
</div>


  <center>
     <p><u>Technologies and processes used in this web app are the following:</u></p>
  </center>
 <div> 
  <center>
      <table style="width:100%">
        <tr>
            <td>Programming language: Ruby</td>
            <td>Scripting: JavaScript</td>
            <td>Database: SQLite</td>
            <td>SASS development IDE: Cloud9</td>
            
        </tr>

        <tr>
            <td>Wep-application framework: Rails</td>
            <td>Version control: BitBucket</td>
            <td>Cloud application platform: Heruko</td>
            <td>Development Methodology: Agile/Scrum, 2 week sprints</td>
        </tr>
      </table>

    </center>
    </div>
    
<%= link_to image_tag("", alt: ""),
            'http' %>
            

    <style>
u { 
    text-decoration: underline;
}
</style>

app/views/static_pages/login.html.erb
<% provide(:title, "Login") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    The Login page body
  </body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages' %>
    
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>